# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
include:
  - board: lpgalaxy_blank_slate
    snippet: studio-rpc-usb-uart
    artifact-name: blank-slate
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: seeeduino-xiao-ble-settings-reset
  - board: seeeduino_xiao_ble
    shield: forager_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: forager-dongle-left
  - board: seeeduino_xiao_ble
    shield: forager_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: forager-dongle-right
  - board: seeeduino_xiao_ble
    shield: dongle_screen
    artifact-name: forager-dongle-screen
